#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_NONE        0
#define MUGSHOT_SIDNEY      1
#define MUGSHOT_PHOEBE      2
#define MUGSHOT_GLACIA      3
#define MUGSHOT_DRAKE       4
#define MUGSHOT_CHAMPION    5

#define MUGSHOT_MAY         6
#define MUGSHOT_BRENDAN     7

#define MUGSHOT_ROXANNE     8
#define MUGSHOT_BRAWLY      9
#define MUGSHOT_WATTSON     10
#define MUGSHOT_FLANNERY    11
#define MUGSHOT_NORMAN      12
#define MUGSHOT_WINONA      13
#define MUGSHOT_TATELIZA    14
#define MUGSHOT_JUAN        15

#define MUGSHOT_WALLY       16
#define MUGSHOT_STEVEN      17

#define MUGSHOT_MAXIE       18
#define MUGSHOT_ARCHIE      19

#define LAST_MUGSHOT        MUGSHOT_ARCHIE
#define MUGSHOTS_COUNT      (LAST_MUGSHOT + 1)

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H